### PR TITLE
Add ListAssert.has(Condition, Index)

### PR DESCRIPTION
**Pull request by Lugribossk**
A ListAssert.has(Condition, Index) similar to ListAssert.contains(T, Index) would be pretty convenient for more fluently readable conditions on individual list elements.

``` java
assertThat(list.get(0)).has(condition);
assertThat(list.get(1)).has(otherCondition);
// Could instead be:
assertThat(list).has(condition, atIndex(0))
                .has(otherCondition, atIndex(1));
```

I can also write up the is() version if you're interested.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
@Bo we have formatting preferences if you are using eclipse et idea they are here mentioned in the contributors guide :
https://github.com/alexruiz/fest-assert-2.x/wiki/Contributor-guidelines

**Comment by Lugribossk** [comment]
Ah great, you have an IDEA version now as well, I'll try applying that one to the code.

**Comment by Lugribossk** [comment]
Looks like I accidentally converted the newlines to Windows-style, which made the entire file look changed. I also added the changes to a [new branch](https://github.com/Lugribossk/fest-assert-2.x/commit/c0e498935c56a3c44bb607d195f4ffaf0c0e7f65) where the diff is readable.

**Comment by joel-costigliola** [comment]
Thanks Bo ! (sorry to have waited so long integrating your work)
If you are up to add the is() alternative, that would be great.

**Pull request merged**
