### PR TITLE
FEST-468

### PR DESCRIPTION
**Pull request by nfrancois**
Here my contribution

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Nice work ! A few comments nevertheless.

_comment 1_

To be consistent with the existing is/isNot/has/hasNot assertions, I would prefer renaming assertions :
- eachElementIs by : are
- eachElementIsNot by : areNot
- eachElementHas by : have
- eachElementHasNot by : doNotHave

Let's see how on works on an example 

``` java
// before
assertThat(set("Luke", "Yoda")).eachElementIs(jedi);
assertThat(set("Leia", "Solo")).eachElementIsNot(jedi);
// after
assertThat(set("Luke", "Yoda")).are(jedi);
assertThat(set("Leia", "Solo")).areNot(jedi);
```

with 'jedi' condition being 

``` java
  private final Condition<String> jedi = new Condition<String>("jedi") {
    private final Set<String> jedis = set("Luke", "Yoda", "Obiwan");
    @Override
    public boolean matches(String value) {
      return jedis.contains(value);
    };
  };
```

have/doNotHave

``` java
// before
assertThat(set("Luke", "Yoda")).eachElementHas(jediPower);
assertThat(set("Leia", "Solo")).eachElementHasNot(jediPower);
// after
assertThat(set("Luke", "Yoda")).have(jediPower);
assertThat(set("Leia", "Solo")).doNotHave(jediPower);
```

With jediPower condition being 

``` java
private final Condition<String> jediPower = new Condition<String>("jedi power") {
// same as jedi condition, only the description is different, it works better on error message 
```

_comment 2_

Duplicated code in Iterables and Arrays (assertEachElementIs and assertEachElementHas)
The following code could be extracted in method assertConditionNotNull
      if (condition == null) throw new NullPointerException("The condition to evaluate should not be null");

_comment 3_

The jedi condition is duplicated in the tests (Iterables_assertEachElementIs_Test, ObjectArrays_assertEachElementHasNot_Test, ... ), let's extract it to its own class.
Even better let's make 2 classes, jedi for are/areNot tests and jediPower for have/doNotHave

---

I can take care of that stuff or I can let you handle that, it's as you wish

Thanks again for your work ! 
Cheers,

Joel

**Comment by nfrancois** [comment]
Hi Joel

Thanks.
I can do it, it's quicky to do.

On comment 2, I think assertConditionNotNull could be a shared with verifyIsNotNull in Conditions by renaming it and put it public and providing a instance of Conditions in Interables and ObjectArrays. So all another features that needs to check this ca do it easily.
What do you think of it ? 

Regarding error message, I named classes EachElementShouldBe, EachElementShouldHave, .... but I think it's not the best name and I have no other ideas. Did you got ?

Nicolas

**Comment by joel-costigliola** [comment]
Good point, let's move assertConditionNotNull in Conditions and use the Conditions  singleton in Iterables and ObjectArrays.

On error classes, we may use ElementsShouldBe or AllElementsShouldBe instead of EachElementShouldBe, I think it is slightly better even though it's not perfect. WDYT ?

We should also rename ShouldBeSameGenericBetweenIterableAndCondition to  ConditionAndGroupGenericParameterTypeShouldBeTheSame, because :
- Group is better than Iterable since the error is used for both iterables and arrays.
- When writing List<E>, E is the generic parameter type, thus the name (see the excellent  http://www.angelikalanger.com/GenericsFAQ/FAQSections/Fundamentals.html for details)

**Comment by nfrancois** [comment]
This is done.

PS : The "unknow" is because I git commit from a another computer whithout my git profile.

**Comment by joel-costigliola** [comment]
Thanks for your work Nicolas.

**Pull request merged**
