### PR TITLE
Introduce InputStream assertions

### PR DESCRIPTION
**Pull request by mbaechler**
Hi,
I needed assertions for InputStreams, so there it is.

I choose not to implement my assertion using "fluent" pattern because InputStream are not necessarily markable, so we can't always chain assertions.

Improvements are indeed possible if InputStream support markable, maybe I'll do it later.

Tell me what you think about it.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Hi Markus,

I have fetch your fest-assert.2.x master branch but it won't compile because it can't find org.fest.util.InputStreamsException;
I don't see a fest-util fork on your github dashboard that I could fetch to get it.

Am i missing something ?

Regards,

Joel

**Comment by mbaechler** [comment]
You're right, I forgot to fork and push my changes on fest-util.
I'll do it monday.

Regards,

Matthieu

**Comment by mbaechler** [comment]
I forked fest-util and push the commit here : https://github.com/mbaechler/fest-util/commit/596822cecff87318e0338a7e9bd4194684ee6eb9

**Comment by joel-costigliola** [comment]
Cool, I'll get a look :)

To integrate InputStream assertions, I will probably have to cherry pick
some of your commit since your master branch includes both InputStream and
Iterables assertions.

A better way to organize stuff would have been to create branches for each
features (branches named according to the corresponding JIRA ticket for
example), it makes it easier to review and integrate features. Maybe it was
possible to make two pull request ... I don't know.

Anyway, I will manage to integrate both, it should not be very difficult
(although the master branch has changed a lot since you forked it).

Thanks again !

Joel

On Mon, Jan 23, 2012 at 9:26 AM, mbaechler <
reply@reply.github.com

**Comment by mbaechler** [comment]
I understand your comments about branch management and pull request.
If you want me to rebase my work on your last master, just ask and I'll do it.

Regards,

## 

Matthieu

On Mon, Jan 23, 2012 at 2:16 PM, Joel Costigliola
reply@reply.github.com
wrote:

**Comment by joel-costigliola** [comment]
No, don't worry, I'll handle it, I'm the author of the commit that caused
conflicts with yours so it should not be difficult for me to do the merge.

Anyway, thanks for proposing.

On Mon, Jan 23, 2012 at 2:33 PM, mbaechler <
reply@reply.github.com

> wrote:
> 
> ent and pull request.
> If you want me to rebase my work on your last master, just ask and I'll do
> it.
> 
> Regards,

**Comment by joel-costigliola** [comment]
I have Integrated your InputStream assertions and made two minor
modifications :
- InputStreamsException is in fest-assert project as it was only used
  there and not in fest-util
- InputStreamAssert allows chained assertions to write stuff like :

assertThat(stream).isNotNull().hasContentEqualTo(otherStream)
maybe later we will enrich streams assertions and it might be useful to
chain them (last reason is to be consistent with fest api)

I will look later at Iterables assertions.

**Pull request closed without merging**
