### PR TITLE
Type safe condition

### PR DESCRIPTION
**Pull request by ash2k**
Improve type safety of Condition assertions.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Hi Mikhail,

I have got a weird compilation error when using maven that I don't have in eclipse, although eclipse project configuration is generated from maven.

```
[INFO] Compilation failure

/home/joe/workspace/fest-assert-2.x/src/main/java/org/fest/assertions/condition/Join.java:[42,38] type parameters of <T>java.util.List<org.fest.assertions.core.Condition<? super T>> cannot be determined; no unique maximal instance exists for type variable T with upper bounds T,java.lang.Object

/home/joe/workspace/fest-assert-2.x/src/main/java/org/fest/assertions/condition/Join.java:[59,38] type parameters of <T>java.util.List<org.fest.assertions.core.Condition<? super T>> cannot be determined; no unique maximal instance exists for type variable T with upper bounds T,java.lang.Object
```

Do you have the same error in Maven ?

**Comment by ash2k** [comment]
@joel-costigliola,
that is probably some compiler issue. I see this neither in Eclipse nor in direct maven build.
I use

```
$ mvn -version
Apache Maven 3.0.4 (r1232337; 2012-01-17 14:44:56+0600)
Maven home: /home/mazursky/programs/apache-maven-3.0.4
Java version: 1.7.0_03, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: ru_RU, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-24-generic", arch: "amd64", family: "unix"
$ java -version
java version "1.7.0_03"
OpenJDK Runtime Environment (IcedTea7 2.1.1pre) (7~u3-2.1.1~pre1-1ubuntu2)
OpenJDK 64-Bit Server VM (build 22.0-b10, mixed mode)
```

Anyway i refactored this piece a little bit - does that help?

**Comment by joel-costigliola** [comment]
Ok, I'll change my compiler to see if it solves the problem

**Comment by joel-costigliola** [comment]
Thanks, your latest commit fixed my (weird) compilation problem !

**Pull request merged**
